-- 临时关闭外键检查
SET FOREIGN_KEY_CHECKS = 0;

-- 删除所有数据
DELETE FROM `rsm_hidden_trouble`;
DELETE FROM `rsm_unverified_risk`;
DELETE FROM `sys_user`;
DELETE FROM `rsm_snapshot`;
DELETE FROM `rsm_patrol_point`;
DELETE FROM `rsm_patrol_list`;
DELETE FROM `rsm_task`;
DELETE FROM `rsm_risk`;

-- Generate fake data for sys_user
INSERT INTO `sys_user` (`dept_id`, `user_name`, `nick_name`, `user_type`, `email`, `phonenumber`, `sex`, `avatar`, `password`, `status`, `del_flag`, `login_ip`, `login_date`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `open_id`)
VALUES
(1, 'admin', '管理员', '00', 'admin@example.com', '15800000001', '1', 'https://ui-avatars.com/api/?name=Elon+', MD5('password1'), '0', '0', '127.0.0.1', NOW(), 'system', NOW(), 'system', NOW(), '系统管理员', 'open_id1'),
(2, 'user1', '用户1', '00', 'user1@example.com', '15800000002', '0', 'https://ui-avatars.com/api/?name=Elon+', MD5('password2'), '0', '0', '127.0.0.1', NOW(), 'admin', NOW(), 'admin', NOW(), '普通用户', 'open_id2'),
(3, 'user2', '用户2', '00', 'user2@example.com', '15800000003', '1', 'https://ui-avatars.com/api/?name=Elon+', MD5('password3'), '0', '0', '127.0.0.1', NOW(), 'admin', NOW(), 'admin', NOW(), '普通用户', 'open_id3'),
(4, 'user3', '用户3', '00', 'user3@example.com', '15800000004', '0', 'https://ui-avatars.com/api/?name=Elon+', MD5('password4'), '0', '0', '127.0.0.1', NOW(), 'admin', NOW(), 'admin', NOW(), '安全主管', 'open_id4'),
(5, 'user4', '用户4', '00', 'user4@example.com', '15800000005', '1', 'https://ui-avatars.com/api/?name=Elon+', MD5('password5'), '0', '0', '127.0.0.1', NOW(), 'admin', NOW(), 'admin', NOW(), '生产主管', 'open_id5'),
(6, 'user5', '用户5', '00', 'user5@example.com', '15800000006', '0', 'https://ui-avatars.com/api/?name=Elon+', MD5('password6'), '0', '0', '127.0.0.1', NOW(), 'admin', NOW(), 'admin', NOW(), '设备主管', 'open_id6'),
(7, 'user6', '用户6', '00', 'user6@example.com', '15800000007', '1', 'https://ui-avatars.com/api/?name=Elon+', MD5('password7'), '0', '0', '127.0.0.1', NOW(), 'admin', NOW(), 'admin', NOW(), '巡检员', 'open_id7'),
(8, 'user7', '用户7', '00', 'user7@example.com', '15800000008', '0', 'https://ui-avatars.com/api/?name=Elon+', MD5('password8'), '0', '0', '127.0.0.1', NOW(), 'admin', NOW(), 'admin', NOW(), '维修工程师', 'open_id8'),
(9, 'user8', '用户8', '00', 'user8@example.com', '15800000009', '1', 'https://ui-avatars.com/api/?name=Elon+', MD5('password9'), '0', '0', '127.0.0.1', NOW(), 'admin', NOW(), 'admin', NOW(), '安全检查员', 'open_id9'),
(10, 'user9', '用户9', '00', 'user9@example.com', '15800000010', '0', 'https://ui-avatars.com/api/?name=Elon+', MD5('password10'), '0', '0', '127.0.0.1', NOW(), 'admin', NOW(), 'admin', NOW(), '风险评估专员', 'open_id10'),
(11, 'user10', '用户10', '00', 'user10@example.com', '15800000011', '1', 'https://ui-avatars.com/api/?name=Elon+', MD5('password11'), '0', '0', '127.0.0.1', NOW(), 'admin', NOW(), 'admin', NOW(), '生产主管', 'open_id11'),
(12, 'user11', '用户11', '00', 'user11@example.com', '15800000012', '0', 'https://ui-avatars.com/api/?name=Elon+', MD5('password12'), '0', '0', '127.0.0.1', NOW(), 'admin', NOW(), 'admin', NOW(), '设备维护员', 'open_id12'),
(13, 'user12', '用户12', '00', 'user12@example.com', '15800000013', '1', 'https://ui-avatars.com/api/?name=Elon+', MD5('password13'), '0', '0', '127.0.0.1', NOW(), 'admin', NOW(), 'admin', NOW(), '安全培训师', 'open_id13'),
(14, 'user13', '用户13', '00', 'user13@example.com', '15800000014', '0', 'https://ui-avatars.com/api/?name=Elon+', MD5('password14'), '0', '0', '127.0.0.1', NOW(), 'admin', NOW(), 'admin', NOW(), '环保监测员', 'open_id14'),
(15, 'user14', '用户14', '00', 'user14@example.com', '15800000015', '1', 'https://ui-avatars.com/api/?name=Elon+', MD5('password15'), '0', '0', '127.0.0.1', NOW(), 'admin', NOW(), 'admin', NOW(), '质量控制员', 'open_id15'),
(16, 'user15', '用户15', '00', 'user15@example.com', '15800000016', '0', 'https://ui-avatars.com/api/?name=Elon+', MD5('password16'), '0', '0', '127.0.0.1', NOW(), 'admin', NOW(), 'admin', NOW(), '物资管理员', 'open_id16'),
(17, 'user16', '用户16', '00', 'user16@example.com', '15800000017', '1', 'https://ui-avatars.com/api/?name=Elon+', MD5('password17'), '0', '0', '127.0.0.1', NOW(), 'admin', NOW(), 'admin', NOW(), '应急救援员', 'open_id17'),
(18, 'user17', '用户17', '00', 'user17@example.com', '15800000018', '0', 'https://ui-avatars.com/api/?name=Elon+', MD5('password18'), '0', '0', '127.0.0.1', NOW(), 'admin', NOW(), 'admin', NOW(), '通风工程师', 'open_id18'),
(19, 'user18', '用户18', '00', 'user18@example.com', '15800000019', '1', 'https://ui-avatars.com/api/?name=Elon+', MD5('password19'), '0', '0', '127.0.0.1', NOW(), 'admin', NOW(), 'admin', NOW(), '地质勘探员', 'open_id19'),
(20, 'user19', '用户19', '00', 'user19@example.com', '15800000020', '0', 'https://ui-avatars.com/api/?name=Elon+', MD5('password20'), '0', '0', '127.0.0.1', NOW(), 'admin', NOW(), 'admin', NOW(), '爆破专员', 'open_id20'),
(21, 'user20', '用户20', '00', 'user20@example.com', '15800000021', '1', 'https://ui-avatars.com/api/?name=Elon+', MD5('password21'), '0', '0', '127.0.0.1', NOW(), 'admin', NOW(), 'admin', NOW(), '电气工程师', 'open_id21'),
(22, 'user21', '用户21', '00', 'user21@example.com', '15800000022', '0', 'https://ui-avatars.com/api/?name=Elon+', MD5('password22'), '0', '0', '127.0.0.1', NOW(), 'admin', NOW(), 'admin', NOW(), '机械工程师', 'open_id22'),
(23, 'user22', '用户22', '00', 'user22@example.com', '15800000023', '1', 'https://ui-avatars.com/api/?name=Elon+', MD5('password23'), '0', '0', '127.0.0.1', NOW(), 'admin', NOW(), 'admin', NOW(), '采矿工程师', 'open_id23'),
(24, 'user23', '用户23', '00', 'user23@example.com', '15800000024', '0', 'https://ui-avatars.com/api/?name=Elon+', MD5('password24'), '0', '0', '127.0.0.1', NOW(), 'admin', NOW(), 'admin', NOW(), '选矿工程师', 'open_id24'),
(25, 'user24', '用户24', '00', 'user24@example.com', '15800000025', '1', 'https://ui-avatars.com/api/?name=Elon+', MD5('password25'), '0', '0', '127.0.0.1', NOW(), 'admin', NOW(), 'admin', NOW(), '测绘工程师', 'open_id25'),
(26, 'user25', '用户25', '00', 'user25@example.com', '15800000026', '0', 'https://ui-avatars.com/api/?name=Elon+', MD5('password26'), '0', '0', '127.0.0.1', NOW(), 'admin', NOW(), 'admin', NOW(), '安全监察员', 'open_id26'),
(27, 'user26', '用户26', '00', 'user26@example.com', '15800000027', '1', 'https://ui-avatars.com/api/?name=Elon+', MD5('password27'), '0', '0', '127.0.0.1', NOW(), 'admin', NOW(), 'admin', NOW(), '设备操作员', 'open_id27'),
(28, 'user27', '用户27', '00', 'user27@example.com', '15800000028', '0', 'https://ui-avatars.com/api/?name=Elon+', MD5('password28'), '0', '0', '127.0.0.1', NOW(), 'admin', NOW(), 'admin', NOW(), '运输调度员', 'open_id28'),
(29, 'user28', '用户28', '00', 'user28@example.com', '15800000029', '1', 'https://ui-avatars.com/api/?name=Elon+', MD5('password29'), '0', '0', '127.0.0.1', NOW(), 'admin', NOW(), 'admin', NOW(), '仓库管理员', 'open_id29'),
(30, 'user29', '用户29', '00', 'user29@example.com', '15800000030', '0', 'https://ui-avatars.com/api/?name=Elon+', MD5('password30'), '0', '0', '127.0.0.1', NOW(), 'admin', NOW(), 'admin', NOW(), '人力资源专员', 'open_id30'),
(31, 'user30', '用户30', '00', 'user30@example.com', '15800000031', '1', 'https://ui-avatars.com/api/?name=Elon+', MD5('password31'), '0', '0', '127.0.0.1', NOW(), 'admin', NOW(), 'admin', NOW(), '财务专员', 'open_id31'),
(32, 'user31', '用户31', '00', 'user31@example.com', '15800000032', '0', 'https://ui-avatars.com/api/?name=Elon+', MD5('password32'), '0', '0', '127.0.0.1', NOW(), 'admin', NOW(), 'admin', NOW(), '信息技术支持', 'open_id32'),
(33, 'user32', '用户32', '00', 'user32@example.com', '15800000033', '1', 'https://ui-avatars.com/api/?name=Elon+', MD5('password33'), '0', '0', '127.0.0.1', NOW(), 'admin', NOW(), 'admin', NOW(), '法律顾问', 'open_id33'),
(34, 'user33', '用户33', '00', 'user33@example.com', '15800000034', '0', 'https://ui-avatars.com/api/?name=Elon+', MD5('password34'), '0', '0', '127.0.0.1', NOW(), 'admin', NOW(), 'admin', NOW(), '公关专员', 'open_id34'),
(35, 'user34', '用户34', '00', 'user34@example.com', '15800000035', '1', 'https://ui-avatars.com/api/?name=Elon+', MD5('password35'), '0', '0', '127.0.0.1', NOW(), 'admin', NOW(), 'admin', NOW(), '市场分析师', 'open_id35'),
(36, 'user35', '用户35', '00', 'user35@example.com', '15800000036', '0', 'https://ui-avatars.com/api/?name=Elon+', MD5('password36'), '0', '0', '127.0.0.1', NOW(), 'admin', NOW(), 'admin', NOW(), '客户服务代表', 'open_id36'),
(37, 'user36', '用户36', '00', 'user36@example.com', '15800000037', '1', 'https://ui-avatars.com/api/?name=Elon+', MD5('password37'), '0', '0', '127.0.0.1', NOW(), 'admin', NOW(), 'admin', NOW(), '研发工程师', 'open_id37'),
(38, 'user37', '用户37', '00', 'user37@example.com', '15800000038', '0', 'https://ui-avatars.com/api/?name=Elon+', MD5('password38'), '0', '0', '127.0.0.1', NOW(), 'admin', NOW(), 'admin', NOW(), '项目经理', 'open_id38'),
(39, 'user38', '用户38', '00', 'user38@example.com', '15800000039', '1', 'https://ui-avatars.com/api/?name=Elon+', MD5('password39'), '0', '0', '127.0.0.1', NOW(), 'admin', NOW(), 'admin', NOW(), '质量保证专员', 'open_id39'),
(40, 'user39', '用户39', '00', 'user39@example.com', '15800000040', '0', 'https://ui-avatars.com/api/?name=Elon+', MD5('password40'), '0', '0', '127.0.0.1', NOW(), 'admin', NOW(), 'admin', NOW(), '数据分析师', 'open_id40');

-- Generate fake data for rsm_risk
INSERT INTO `rsm_risk` (`risk_name`, `risk_type`, `supervisor`, `control_standard`, `position`, `risk_level`, `risk_info`, `risk_relate_id`, `auditor`, `risk_describe`, `risk_conseq`, `control_measure`, `remark`, `create_by`, `create_time`, `update_by`, `update_time`)
VALUES
('矿井通风系统风险', '作业风险', '张三', '定期检查通风系统，确保空气质量达标', '主井通风系统', 'B', '矿井通风系统', 1, '李四', '矿井通风系统存在有害气体和粉尘吸入风险', '可能导致工人吸入有害气体或粉尘，影响健康', '增加通风系统检查频率，定期更换过滤装置', '需要携带气体检测仪和防尘面具', 'admin', NOW(), 'admin', NOW()),
('矿山支护结构风险', '生产现场风险', '王五', '定期检查支护结构，及时加固薄弱部位', '东区采场支护结构', 'A', '矿山支护结构', 2, '赵六', '矿山支护结构存在顶板塌陷和片帮冒顶风险', '可能导致严重的安全事故，造成人员伤亡和财产损失', '增加支护结构检查频率，使用先进监测设备', '携带专业检测设备，注意安全防护', 'admin', NOW(), 'admin', NOW()),
('矿车制动系统风险', '设备风险', '周九', '定期检查和维护矿车制动系统', '矿车维修车间', 'C', '矿车制动系统', 3, '吴十', '矿车制动系统老化，可能导致制动失效', '可能导致矿车失控，造成事故', '定期更换制动系统，加强日常维护', '需要提前协调生产计划', 'admin', NOW(), 'admin', NOW()),
('井下排水系统风险', '设备风险', '刘一', '定期检查排水泵和管道系统', '井下排水系统', 'B', '井下排水系统', 4, '陈二', '井下排水泵存在老化现象，可能导致排水不畅', '可能导致井下积水，影响生产安全', '更换老化泵体，增加备用泵，定期清理管道', '携带防水设备和应急照明', 'admin', NOW(), 'admin', NOW()),
('矿井电力系统风险', '设备风险', '孙七', '定期检查电力线路和设备', '矿井供电系统', 'A', '矿井电力系统', 5, '周八', '部分电力线路绝缘老化，存在短路风险', '可能导致停电或火灾，影响生产安全', '更换老化线路，加强日常巡检，安装漏电保护装置', '需要专业电工和绝缘防护装备', 'admin', NOW(), 'admin', NOW()),
('矿井提升系统风险', '设备风险', '郑十一', '定期检查提升系统各部件', '主井提升系统', 'A', '矿井提升系统', 6, '钱十二', '提升系统钢丝绳出现磨损，存在断裂风险', '可能导致提升系统故障，造成人员伤亡', '定期更换磨损钢丝绳，进行无损探伤检测', '需要专业机械工程师', 'admin', NOW(), 'admin', NOW()),
('爆破作业风险', '作业风险', '孟十三', '严格执行爆破作业规程', '采矿区域', 'A', '爆破作业', 7, '冯十四', '爆破作业可能引发岩石飞溅或诱发地压', '可能造成人员伤亡或设备损坏', '制定详细的爆破计划，设置安全警戒区', '需要专业爆破人员操作', 'admin', NOW(), 'admin', NOW()),
('矿井瓦斯积聚风险', '生产现场风险', '蒋十五', '实时监测瓦斯浓度，保持良好通风', '采煤工作面', 'A', '瓦斯积聚', 8, '韩十六', '采煤过程中可能造成瓦斯突然积聚', '可能引发瓦斯爆炸，造成重大伤亡', '安装瓦斯监测系统，制定应急预案', '配备便携式瓦斯检测仪', 'admin', NOW(), 'admin', NOW()),
('矿井水灾风险', '生产现场风险', '江十七', '加强水文地质勘探，完善防水设施', '井下各区域', 'B', '水灾', 9, '何十八', '可能遭遇突发性涌水或溃水', '可能导致井下淹没，造成人员伤亡', '建立完善的排水系统，准备应急抽水设备', '定期进行防水演练', 'admin', NOW(), 'admin', NOW()),
('粉尘爆炸风险', '生产现场风险', '吕十九', '控制粉尘浓度，消除点火源', '煤仓和输送系统', 'B', '粉尘爆炸', 10, '施二十', '煤尘积聚可能引发粉尘爆炸', '可能造成设备损坏和人员伤亡', '安装粉尘抑制系统，定期清理积尘', '配备防爆电气设备', 'admin', NOW(), 'admin', NOW()),
('高温作业风险', '作业风险', '彭二一', '监控作业环境温度，采取降温措施', '深部采矿区', 'C', '高温作业', 11, '葛二二', '深部开采面临高温环境', '可能导致中暑等健康问题', '安装降温设备，合理安排工作时间', '提供防暑降温用品', 'admin', NOW(), 'admin', NOW()),
('有毒气体中毒风险', '生产现场风险', '程二三', '加强有毒气体监测，保持良好通风', '井下各区域', 'B', '有毒气体', 12, '董二四', '开采过程可能释放CO、H2S等有毒气体', '可能导致人员中毒', '安装气体监测报警系统，配备个人防护设备', '定期进行应急救援演练', 'admin', NOW(), 'admin', NOW()),
('机械伤害风险', '设备风险', '谢二五', '规范操作流程，加强设备防护', '采矿设备操作区', 'C', '机械伤害', 13, '赖二六', '采矿设备操作不当可能造成机械伤害', '可能导致人员受伤', '加强操作培训，完善设备防护装置', '配备个人防护用品', 'admin', NOW(), 'admin', NOW()),
('坠落风险', '作业风险', '范二七', '加强高处作业管理，完善防护设施', '井筒维修、高处作业区域', 'B', '高处坠落', 14, '汪二八', '高处作业存在坠落风险', '可能造成严重人身伤害', '安装防坠落系统，使用安全带', '定期检查维护安全设施', 'admin', NOW(), 'admin', NOW()),
('职业病风险', '其他', '杜二九', '控制粉尘、噪声等职业病危害因素', '全矿区', 'C', '职业病', 15, '沈三十', '长期接触粉尘、噪声等可能引发职业病', '影响员工健康，增加企业负担', '改善作业环境，定期体检，轮岗制度', '加强职业健康教育', 'admin', NOW(), 'admin', NOW()),
('地质灾害风险', '生产现场风险', '范三一', '加强地质勘探和监测', '采矿区域', 'A', '地质灾害', 16, '金三二', '可能发生滑坡、塌陷等地质灾害', '可能造成重大人员伤亡和财产损失', '建立地质灾害监测预警系统，制定应急预案', '定期进行地质勘探', 'admin', NOW(), 'admin', NOW()),
('井下火灾风险', '生产现场风险', '夏三三', '加强防火管理，配备消防设备', '井下各区域', 'A', '井下火灾', 17, '唐三四', '电气设备故障或易燃物品引发火灾', '可能造成人员伤亡和设备损坏', '安装火灾报警系统，配备灭火设备', '定期进行消防演练', 'admin', NOW(), 'admin', NOW()),
('矿井突水风险', '生产现场风险', '柳三五', '加强水文地质勘探，完善防水设施', '井下采掘工作面', 'A', '突水', 18, '石三六', '可能遭遇突发性涌水或溃水', '可能导致井下淹没，造成人员伤亡', '建立完善的排水系统，准备应急抽水设备', '定期进行防水演练', 'admin', NOW(), 'admin', NOW()),
('井下运输事故风险', '作业风险', '廖三七', '规范运输操作，加强设备维护', '井下运输系统', 'B', '运输事故', 19, '贾三八', '运输过程中可能发生碰撞、脱轨等事故', '可能造成人员伤亡和设备损坏', '加强运输人员培训，定期检修运输设备', '建立运输安全管理制度', 'admin', NOW(), 'admin', NOW()),
('矿井通信中断风险', '设备风险', '姜三九', '定期检查通信系统，配备备用设备', '井下通信系统', 'B', '通信中断', 20, '戚四十', '通信系统故障可能导致井上井下通信中断', '影响生产指挥和应急救援', '定期维护通信设备，配备备用通信系统', '建立应急通信方案', 'admin', NOW(), 'admin', NOW()),
('井下设备故障风险', '设备风险', '谭四一', '加强设备维护，建立备用系统', '井下各类设备', 'B', '设备故障', 21, '包四二', '关键设备故障可能影响生产安全', '可能导致生产中断或安全事故', '建立设备维护保养制度，储备关键备件', '培训维修人员，提高故障处理能力', 'admin', NOW(), 'admin', NOW()),
('矿井地压风险', '生产现场风险', '樊四三', '加强地压监测，优化采矿方法', '采掘工作面', 'A', '地压', 22, '邹四四', '采矿活动可能引发地压活动', '可能导致冒顶、片帮等事故', '安装地压监测系统，优化支护方案', '制定地压应急预案', 'admin', NOW(), 'admin', NOW()),
('井下触电风险', '设备风险', '滕四五', '加强电气设备管理，规范操作流程', '井下供电系统', 'B', '触电', 23, '殷四六', '电气设备故障或操作不当可能导致触电', '可能造成人员伤亡', '定期检查电气设备，使用防触电装置', '加强电气安全培训', 'admin', NOW(), 'admin', NOW()),
('矿井废水污染风险', '其他', '贺四七', '加强废水处理，防止污染扩散', '矿井排水系统', 'C', '水污染', 24, '雷四八', '矿井废水可能污染地下水和地表水', '影响环境和周边居民健康', '建设完善的废水处理系统，定期监测水质', '制定水污染应急预案', 'admin', NOW(), 'admin', NOW()),
('井下中毒和窒息风险', '生产现场风险', '倪四九', '加强有害气体监测，保持良好通风', '井下密闭空间', 'A', '中毒窒息', 25, '汤五十', '密闭空间可能积聚有害气体或缺氧', '可能导致人员中毒或窒息', '配备个人防护设备，加强通风措施', '定期进行气体检测', 'admin', NOW(), 'admin', NOW());


-- Generate fake data for rsm_task
INSERT INTO `rsm_task` (`task_name`, `type_name`, `dept_name`, `start_time`, `end_time`, `risk_id`, `mandate_holder`, `approval_status`, `reviewer`, `task_desc`, `position_info`, `create_by`, `remark`, `create_time`, `update_by`, `update_time`)
VALUES
('矿石开采', '日常生产', '采矿部', '2023-06-01 08:00:00', '2023-06-03 17:00:00', 7, '张三', 1, '李四', '在东区采场进行矿石开采作业', '东区采场', 'admin', '按计划完成开采任务', NOW(), 'admin', NOW()),
('矿石运输', '日常生产', '运输部', '2023-06-05 07:30:00', '2023-06-07 18:00:00', 1, '王五', 0, '赵六', '将开采的矿石运送至选矿厂', '矿区至选矿厂运输路线', 'admin', '确保运输安全，避免矿石遗撒', NOW(), 'admin', NOW()),
('选矿作业', '日常生产', '选矿部', '2023-06-10 09:00:00', '2023-06-12 16:00:00', 2, '周九', 2, '吴十', '对运送来的矿石进行筛选和加工', '选矿厂', 'admin', '提高矿石品位，减少杂质', NOW(), 'admin', NOW()),
('设备维护', '设备保养', '机械部', '2023-06-15 08:00:00', '2023-06-17 16:00:00', 3, '刘一', 1, '陈二', '对采矿设备进行定期维护和保养', '设备维修车间', 'admin', '确保设备正常运转，延长使用寿命', NOW(), 'admin', NOW()),
('安全培训', '安全教育', '安全部', '2023-06-20 09:00:00', '2023-06-20 17:00:00', 4, '孙七', 2, '周八', '对全体员工进行安全生产培训', '培训中心', 'admin', '提高员工安全意识，减少事故发生', NOW(), 'admin', NOW()),
('环境监测', '环境保护', '环保部', '2023-06-25 07:00:00', '2023-06-27 18:00:00', 5, '郑十一', 0, '钱十二', '对矿区周边环境进行例行监测', '矿区及周边区域', 'admin', '确保生产活动符合环保要求', NOW(), 'admin', NOW()),
('矿石破碎', '日常生产', '破碎部', '2023-07-01 08:00:00', '2023-07-03 17:00:00', 6, '赵三', 1, '王四', '对矿石进行破碎处理', '破碎车间', 'admin', '确保破碎效率，减少粉尘', NOW(), 'admin', NOW()),
('矿石筛分', '日常生产', '筛分部', '2023-07-05 07:30:00', '2023-07-07 18:00:00', 7, '李五', 0, '周六', '对破碎后的矿石进行筛分', '筛分车间', 'admin', '提高筛分精度，减少杂质', NOW(), 'admin', NOW()),
('矿石堆存', '日常生产', '堆存部', '2023-07-10 09:00:00', '2023-07-12 16:00:00', 8, '吴七', 2, '郑八', '将筛分后的矿石进行堆存', '堆存场', 'admin', '确保堆存安全，防止滑坡', NOW(), 'admin', NOW()),
('矿石装车', '日常生产', '装车部', '2023-07-15 08:00:00', '2023-07-17 16:00:00', 9, '王九', 1, '李十', '将堆存的矿石装车运送', '装车场', 'admin', '确保装车效率，避免矿石遗撒', NOW(), 'admin', NOW()),
('矿石运输', '日常生产', '运输部', '2023-07-20 09:00:00', '2023-07-22 17:00:00', 10, '赵十一', 2, '周十二', '将矿石运送至港口', '矿区至港口运输路线', 'admin', '确保运输安全，避免矿石遗撒', NOW(), 'admin', NOW()),
('矿石装船', '日常生产', '装船部', '2023-07-25 08:00:00', '2023-07-27 16:00:00', 11, '李十三', 1, '吴十四', '将矿石装船运送', '港口装船区', 'admin', '确保装船效率，避免矿石遗撒', NOW(), 'admin', NOW()),
('矿石出口', '日常生产', '出口部', '2023-07-30 09:00:00', '2023-08-01 17:00:00', 12, '王十五', 2, '赵十六', '办理矿石出口手续', '出口办公室', 'admin', '确保出口手续顺利完成', NOW(), 'admin', NOW()),
('矿石进口', '日常生产', '进口部', '2023-08-05 08:00:00', '2023-08-07 16:00:00', 13, '李十七', 1, '周十八', '办理矿石进口手续', '进口办公室', 'admin', '确保进口手续顺利完成', NOW(), 'admin', NOW()),
('矿石仓储', '日常生产', '仓储部', '2023-08-10 09:00:00', '2023-08-12 17:00:00', 14, '吴十九', 2, '郑二十', '将进口的矿石进行仓储', '仓储区', 'admin', '确保仓储安全，防止矿石损失', NOW(), 'admin', NOW()),
('矿石分发', '日常生产', '分发部', '2023-08-15 08:00:00', '2023-08-17 16:00:00', 15, '王二一', 1, '李二二', '将仓储的矿石分发至各生产单位', '分发区', 'admin', '确保分发效率，避免矿石损失', NOW(), 'admin', NOW()),
('矿石加工', '日常生产', '加工部', '2023-08-20 09:00:00', '2023-08-22 17:00:00', 16, '赵二三', 2, '周二四', '对矿石进行深加工', '加工车间', 'admin', '提高加工效率，减少废料', NOW(), 'admin', NOW()),
('矿石包装', '日常生产', '包装部', '2023-08-25 08:00:00', '2023-08-27 16:00:00', 17, '李二五', 1, '吴二六', '将加工后的矿石进行包装', '包装车间', 'admin', '确保包装质量，防止损坏', NOW(), 'admin', NOW()),
('矿石销售', '日常生产', '销售部', '2023-08-30 09:00:00', '2023-09-01 17:00:00', 18, '王二七', 2, '赵二八', '将包装好的矿石进行销售', '销售办公室', 'admin', '确保销售顺利完成', NOW(), 'admin', NOW()),
('矿石回收', '日常生产', '回收部', '2023-09-05 08:00:00', '2023-09-07 16:00:00', 19, '李二九', 1, '周三十', '对废弃矿石进行回收处理', '回收车间', 'admin', '确保回收效率，减少环境污染', NOW(), 'admin', NOW());

-- Generate fake data for rsm_patrol_list
INSERT INTO `rsm_patrol_list` (`patrol_list_name`, `principal_id`, `start_time`, `end_time`, `checked_count`, `hidden_trouble_count`, `finish_time`, `status`, `del_flag`, `create_by`, `create_time`, `update_time`, `update_by`, `remark`)
VALUES
('矿井通风系统检查', 1, '2023-06-01 08:00:00', '2023-06-03 17:00:00', 10, 2, NOW(), 0, 0, 'admin', NOW(), NOW(), 'admin', '需要携带气体检测仪和防尘面具'),
('矿山支护结构巡检', 2, '2023-06-05 07:30:00', '2023-06-07 18:00:00', 8, 1, NOW(), 0, 0, 'admin', NOW(), NOW(), 'admin', '携带专业检测设备，注意安全防护'),
('矿车制动系统更换', 3, '2023-06-10 09:00:00', '2023-06-12 16:00:00', 12, 3, NOW(), 0, 0, 'admin', NOW(), NOW(), 'admin', '需要提前协调生产计划'),
('井下排水系统检查', 4, '2023-06-15 08:30:00', '2023-06-17 15:30:00', 6, 1, NOW(), 0, 0, 'admin', NOW(), NOW(), 'admin', '携带防水设备和应急照明'),
('矿井电力系统巡检', 5, '2023-06-20 07:00:00', '2023-06-22 18:00:00', 15, 2, NOW(), 0, 0, 'admin', NOW(), NOW(), 'admin', '需要专业电工和绝缘防护装备'),
('矿井提升系统检查', 6, '2023-06-25 08:00:00', '2023-06-27 17:00:00', 9, 2, NOW(), 0, 0, 'admin', NOW(), NOW(), 'admin', '需要专业机械工程师'),
('矿井通信系统巡检', 7, '2023-06-30 09:00:00', '2023-07-02 16:00:00', 7, 1, NOW(), 0, 0, 'admin', NOW(), NOW(), 'admin', '携带通信测试设备'),
('矿井消防系统检查', 8, '2023-07-05 08:30:00', '2023-07-07 15:30:00', 11, 3, NOW(), 0, 0, 'admin', NOW(), NOW(), 'admin', '检查消防设备的有效期'),
('矿石开采作业检查', 9, '2023-07-10 08:00:00', '2023-07-12 17:00:00', 13, 4, NOW(), 0, 0, 'admin', NOW(), NOW(), 'admin', '检查矿石开采作业的安全措施'),
('矿石运输作业检查', 10, '2023-07-15 07:30:00', '2023-07-17 18:00:00', 10, 2, NOW(), 0, 0, 'admin', NOW(), NOW(), 'admin', '确保矿石运输过程中的安全和效率');

-- Generate fake data for rsm_patrol_point
INSERT INTO `rsm_patrol_point` (`patrol_name`, `patrol_desc`, `position`, `location_describe`, `security_officer`, `last_patrol_time`, `patrol_frequency`, `status`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`)
VALUES
('主井通风系统', '矿井主要通风系统位置', '主井通风系统', '主井通风系统', '张三', NOW(), 5, 0, 0, 'admin', NOW(), 'admin', NOW(), '主要通风系统位置'),
('东区采场', '东区采场位置', '东区采场', '东区采场', '赵六', NOW(), 3, 0, 0, 'admin', NOW(), 'admin', NOW(), '主要采场位置'),
('维修车间', '矿车维修车间位置', '维修车间', '维修车间', '周九', NOW(), 7, 0, 0, 'admin', NOW(), 'admin', NOW(), '维修车间位置'),
('排水泵站', '井下排水泵站位置', '排水泵站', '排水泵站', '李四', NOW(), 4, 0, 0, 'admin', NOW(), 'admin', NOW(), '排水泵站位置'),
('变电站', '矿井主要变电站位置', '变电站', '变电站', '王五', NOW(), 6, 0, 0, 'admin', NOW(), 'admin', NOW(), '主要变电站位置'),
('提升机房', '主井提升机房位置', '提升机房', '提升机房', '刘七', NOW(), 5, 0, 0, 'admin', NOW(), 'admin', NOW(), '提升机房位置'),
('通信中心', '矿井通信中心位置', '通信中心', '通信中心', '孙八', NOW(), 4, 0, 0, 'admin', NOW(), 'admin', NOW(), '通信中心位置'),
('消防站', '矿井各层消防站位置', '消防站', '消防站', '钱十', NOW(), 3, 0, 0, 'admin', NOW(), 'admin', NOW(), '消防站位置'),
('破碎车间', '矿石破碎车间位置', '破碎车间', '破碎车间', '吴十一', NOW(), 6, 0, 0, 'admin', NOW(), 'admin', NOW(), '破碎车间位置'),
('筛分车间', '矿石筛分车间位置', '筛分车间', '筛分车间', '郑十二', NOW(), 5, 0, 0, 'admin', NOW(), 'admin', NOW(), '筛分车间位置'),
('堆存场', '矿石堆存场位置', '堆存场', '堆存场', '王十三', NOW(), 4, 0, 0, 'admin', NOW(), 'admin', NOW(), '堆存场位置'),
('装车场', '矿石装车场位置', '装车场', '装车场', '李十四', NOW(), 3, 0, 0, 'admin', NOW(), 'admin', NOW(), '装车场位置'),
('矿井入口', '矿井主要入口位置', '矿井入口', '矿井入口', '陈十五', NOW(), 5, 0, 0, 'admin', NOW(), 'admin', NOW(), '矿井入口位置'),
('矿井出口', '矿井主要出口位置', '矿井出口', '矿井出口', '林十六', NOW(), 4, 0, 0, 'admin', NOW(), 'admin', NOW(), '矿井出口位置'),
('仓库', '矿井仓库位置', '仓库', '仓库', '黄十七', NOW(), 6, 0, 0, 'admin', NOW(), 'admin', NOW(), '仓库位置'),
('办公室', '矿井办公室位置', '办公室', '办公室', '周十八', NOW(), 3, 0, 0, 'admin', NOW(), 'admin', NOW(), '办公室位置'),
('矿井水处理站', '矿井水处理站位置', '水处理站', '水处理站', '吴十九', NOW(), 4, 0, 0, 'admin', NOW(), 'admin', NOW(), '水处理站位置'),
('矿井废料处理站', '矿井废料处理站位置', '废料处理站', '废料处理站', '郑二十', NOW(), 5, 0, 0, 'admin', NOW(), 'admin', NOW(), '废料处理站位置'),
('矿井通风口', '矿井通风口位置', '通风口', '通风口', '赵二十一', NOW(), 4, 0, 0, 'admin', NOW(), 'admin', NOW(), '通风口位置'),
('矿井排水口', '矿井排水口位置', '排水口', '排水口', '钱二十二', NOW(), 3, 0, 0, 'admin', NOW(), 'admin', NOW(), '排水口位置'),
('矿井电力室', '矿井电力室位置', '电力室', '电力室', '孙二十三', NOW(), 5, 0, 0, 'admin', NOW(), 'admin', NOW(), '电力室位置'),
('矿井安全室', '矿井安全室位置', '安全室', '安全室', '李二十四', NOW(), 4, 0, 0, 'admin', NOW(), 'admin', NOW(), '安全室位置');


INSERT INTO `rsm_unverified_risk` (`unverified_risk_name`, `risk_id`, `patrol_list_id`, `risk_type`, `admin`, `control_standard`, `position`, `status`, `remark`, `create_by`, `create_time`, `update_by`, `update_time`)
VALUES
('矿石开采风险', 7, 9, '作业活动', '管理员1', '巡查标准1', 2, 0, '在东区采场进行矿石开采作业', 'admin', NOW(), 'admin', NOW()),
('矿石运输风险', 1, 10, '作业活动', '管理员2', '巡查标准2', 11, 1, '将开采的矿石运送至选矿厂', 'admin', NOW(), 'admin', NOW()),
('选矿作业风险', 2, 9, '作业活动', '管理员3', '巡查标准3', 10, 2, '对运送来的矿石进行筛选和加工', 'admin', NOW(), 'admin', NOW()),
('设备维护风险', 3, 6, '设备设施', '管理员4', '巡查标准4', 3, 0, '对采矿设备进行定期维护和保养', 'admin', NOW(), 'admin', NOW()),
('安全培训风险', 4, 7, '其他', '管理员5', '巡查标准5', 17, 1, '对全体员工进行安全生产培训', 'admin', NOW(), 'admin', NOW()),
('环境监测风险', 5, 6, '其他', '管理员6', '巡查标准6', 18, 0, '对矿区周边环境进行例行监测', 'admin', NOW(), 'admin', NOW()),
('矿石破碎风险', 6, 9, '作业活动', '管理员7', '巡查标准7', 9, 1, '对矿石进行破碎处理', 'admin', NOW(), 'admin', NOW()),
('矿石筛分风险', 7, 9, '作业活动', '管理员8', '巡查标准8', 10, 2, '对破碎后的矿石进行筛分', 'admin', NOW(), 'admin', NOW()),
('矿石堆存风险', 8, 9, '作业活动', '管理员9', '巡查标准9', 11, 0, '将筛分后的矿石进行堆存', 'admin', NOW(), 'admin', NOW()),
('矿石装车风险', 9, 10, '作业活动', '管理员10', '巡查标准10', 12, 1, '将堆存的矿石装车运送', 'admin', NOW(), 'admin', NOW()),
('矿石运输风险', 10, 10, '作业活动', '管理员11', '巡查标准11', 13, 2, '将矿石运送至港口', 'admin', NOW(), 'admin', NOW()),
('矿石装船风险', 11, 10, '作业活动', '管理员12', '巡查标准12', 14, 0, '将矿石装船运送', 'admin', NOW(), 'admin', NOW()),
('矿石出口风险', 12, 10, '作业活动', '管理员13', '巡查标准13', 15, 1, '办理矿石出口手续', 'admin', NOW(), 'admin', NOW()),
('矿石进口风险', 13, 10, '作业活动', '管理员14', '巡查标准14', 16, 2, '办理矿石进口手续', 'admin', NOW(), 'admin', NOW()),
('矿石仓储风险', 14, 10, '作业活动', '管理员15', '巡查标准15', 17, 0, '将进口的矿石进行仓储', 'admin', NOW(), 'admin', NOW()),
('矿石分发风险', 15, 10, '作业活动', '管理员16', '巡查标准16', 18, 1, '将仓储的矿石分发至各生产单位', 'admin', NOW(), 'admin', NOW()),
('矿石加工风险', 16, 10, '作业活动', '管理员17', '巡查标准17', 19, 2, '对矿石进行深加工', 'admin', NOW(), 'admin', NOW()),
('矿石包装风险', 17, 10, '作业活动', '管理员18', '巡查标准18', 20, 0, '将加工后的矿石进行包装', 'admin', NOW(), 'admin', NOW()),
('矿石销售风险', 18, 10, '作业活动', '管理员19', '巡查标准19', 21, 1, '将包装好的矿石进行销售', 'admin', NOW(), 'admin', NOW()),
('矿石回收风险', 19, 10, '作业活动', '管理员20', '巡查标准20', 22, 2, '对废弃矿石进行回收处理', 'admin', NOW(), 'admin', NOW());

-- Generate fake data for rsm_hidden_trouble
INSERT INTO `rsm_hidden_trouble` (`trouble_title`, `creator_id`, `trouble_img_path`, `trouble_desc`, `status`, `trouble_classify`, `source`, `handler_id`, `handle_img_path`, `rectify_desc`, `rectify_time`, `create_time`, `update_time`, `remark`)
VALUES
('矿井通风系统隐患', 1, 'https://registry.npmmirror.com/wot-design-uni-assets/*/files/redpanda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/capybara.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/panda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/moon.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/meng.jpg', '矿井通风系统存在有害气体和粉尘吸入风险', 0, 1, 0, 2, 'https://registry.npmmirror.com/wot-design-uni-assets/*/files/redpanda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/capybara.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/panda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/moon.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/meng.jpg', '更换通风系统过滤装置，增加通风频率', NOW(), NOW(), NOW(), '需要携带气体检测仪和防尘面具'),
('矿山支护结构隐患', 2, 'https://registry.npmmirror.com/wot-design-uni-assets/*/files/redpanda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/capybara.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/panda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/moon.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/meng.jpg', '矿山支护结构存在顶板塌陷和片帮冒顶风险', 1, 2, 1, 3, 'https://registry.npmmirror.com/wot-design-uni-assets/*/files/redpanda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/capybara.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/panda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/moon.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/meng.jpg', '加固支护结构，增加监测点位', NOW(), NOW(), NOW(), '携带专业检测设备，注意安全防护'),
('矿车制动系统隐患', 3, 'https://registry.npmmirror.com/wot-design-uni-assets/*/files/redpanda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/capybara.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/panda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/moon.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/meng.jpg', '矿车制动系统需要短时间停止运输，影响生产效率', 0, 3, 0, 1, 'https://registry.npmmirror.com/wot-design-uni-assets/*/files/redpanda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/capybara.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/panda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/moon.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/meng.jpg', '分批次更换制动系统，保证生产连续性', NOW(), NOW(), NOW(), '需要提前协调生产计划'),
('井下排水系统隐患', 4, 'https://registry.npmmirror.com/wot-design-uni-assets/*/files/redpanda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/capybara.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/panda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/moon.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/meng.jpg', '井下排水泵存在老化现象，可能导致排水不畅', 0, 1, 1, 4, 'https://registry.npmmirror.com/wot-design-uni-assets/*/files/redpanda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/capybara.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/panda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/moon.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/meng.jpg', '更换老化泵体，增加备用泵', NOW(), NOW(), NOW(), '携带防水设备和应急照明'),
('矿井电力系统隐患', 5, 'https://registry.npmmirror.com/wot-design-uni-assets/*/files/redpanda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/capybara.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/panda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/moon.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/meng.jpg', '部分电力线路绝缘老化，存在短路风险', 1, 2, 0, 5, 'https://registry.npmmirror.com/wot-design-uni-assets/*/files/redpanda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/capybara.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/panda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/moon.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/meng.jpg', '更换老化线路，加强日常巡检', NOW(), NOW(), NOW(), '需要专业电工和绝缘防护装备'),
('矿井提升系统隐患', 6, 'https://registry.npmmirror.com/wot-design-uni-assets/*/files/redpanda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/capybara.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/panda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/moon.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/meng.jpg', '提升系统钢丝绳出现磨损，存在断裂风险', 0, 1, 1, 6, 'https://registry.npmmirror.com/wot-design-uni-assets/*/files/redpanda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/capybara.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/panda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/moon.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/meng.jpg', '更换磨损钢丝绳，加强日常检查', NOW(), NOW(), NOW(), '需要专业机械工程师'),
('矿井通信系统隐患', 7, 'https://registry.npmmirror.com/wot-design-uni-assets/*/files/redpanda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/capybara.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/panda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/moon.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/meng.jpg', '部分通信设备信号不稳定，影响井下通讯', 1, 3, 0, 7, 'https://registry.npmmirror.com/wot-design-uni-assets/*/files/redpanda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/capybara.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/panda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/moon.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/meng.jpg', '更换老旧通信设备，优化信号覆盖', NOW(), NOW(), NOW(), '携带通信测试设备'),
('矿井消防系统隐患', 8, 'https://registry.npmmirror.com/wot-design-uni-assets/*/files/redpanda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/capybara.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/panda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/moon.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/meng.jpg', '部分消防设备已过期，存在失效风险', 0, 2, 1, 8, 'https://registry.npmmirror.com/wot-design-uni-assets/*/files/redpanda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/capybara.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/panda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/moon.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/meng.jpg', '更换过期消防设备，完善消防系统', NOW(), NOW(), NOW(), '检查消防设备的有效期'),
('井下瓦斯监测系统隐患', 9, 'https://registry.npmmirror.com/wot-design-uni-assets/*/files/redpanda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/capybara.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/panda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/moon.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/meng.jpg', '部分瓦斯监测设备灵敏度下降，可能导致瓦斯超标无法及时发现', 1, 3, 0, 9, 'https://registry.npmmirror.com/wot-design-uni-assets/*/files/redpanda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/capybara.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/panda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/moon.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/meng.jpg', '更换老化监测设备，增加监测点位', NOW(), NOW(), NOW(), '携带便携式瓦斯检测仪'),
('矿井供电系统隐患', 10, 'https://registry.npmmirror.com/wot-design-uni-assets/*/files/redpanda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/capybara.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/panda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/moon.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/meng.jpg', '部分供电设备老化，存在突发停电风险', 0, 1, 1, 10, 'https://registry.npmmirror.com/wot-design-uni-assets/*/files/redpanda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/capybara.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/panda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/moon.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/meng.jpg', '更换老化供电设备，完善应急供电系统', NOW(), NOW(), NOW(), '准备应急发电机'),
('矿井排水系统隐患', 11, 'https://registry.npmmirror.com/wot-design-uni-assets/*/files/redpanda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/capybara.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/panda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/moon.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/meng.jpg', '部分排水管道存在堵塞风险，可能导致井下积水', 1, 2, 0, 11, 'https://registry.npmmirror.com/wot-design-uni-assets/*/files/redpanda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/capybara.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/panda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/moon.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/meng.jpg', '清理排水管道，增加定期检查频率', NOW(), NOW(), NOW(), '携带排水管道疏通设备'),
('矿井运输系统隐患', 12, 'https://registry.npmmirror.com/wot-design-uni-assets/*/files/redpanda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/capybara.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/panda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/moon.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/meng.jpg', '部分运输设备磨损严重，存在故障风险', 0, 3, 1, 12, 'https://registry.npmmirror.com/wot-design-uni-assets/*/files/redpanda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/capybara.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/panda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/moon.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/meng.jpg', '更换磨损严重的运输设备，加强日常维护', NOW(), NOW(), NOW(), '准备备用运输设备'),
('井下照明系统隐患', 13, 'https://registry.npmmirror.com/wot-design-uni-assets/*/files/redpanda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/capybara.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/panda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/moon.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/meng.jpg', '部分区域照明不足，影响作业安全', 1, 2, 0, 13, 'https://registry.npmmirror.com/wot-design-uni-assets/*/files/redpanda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/capybara.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/panda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/moon.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/meng.jpg', '增加照明设备，优化照明布局', NOW(), NOW(), NOW(), '携带便携式照明设备'),
('矿井通风系统隐患', 14, 'https://registry.npmmirror.com/wot-design-uni-assets/*/files/redpanda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/capybara.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/panda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/moon.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/meng.jpg', '通风系统效率下降，可能导致有害气体积聚', 0, 1, 1, 14, 'https://registry.npmmirror.com/wot-design-uni-assets/*/files/redpanda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/capybara.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/panda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/moon.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/meng.jpg', '检修通风设备，优化通风路径', NOW(), NOW(), NOW(), '携带气体检测仪'),
('矿井排水系统隐患', 15, 'https://registry.npmmirror.com/wot-design-uni-assets/*/files/redpanda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/capybara.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/panda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/moon.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/meng.jpg', '排水管道出现堵塞，可能导致井下积水', 1, 3, 0, 15, 'https://registry.npmmirror.com/wot-design-uni-assets/*/files/redpanda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/capybara.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/panda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/moon.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/meng.jpg', '清理排水管道，增加定期检查频率', NOW(), NOW(), NOW(), '携带排水管道疏通设备'),
('矿井支护系统隐患', 16, 'https://registry.npmmirror.com/wot-design-uni-assets/*/files/redpanda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/capybara.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/panda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/moon.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/meng.jpg', '部分支护结构出现变形，存在坍塌风险', 0, 2, 1, 16, 'https://registry.npmmirror.com/wot-design-uni-assets/*/files/redpanda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/capybara.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/panda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/moon.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/meng.jpg', '加固变形支护结构，增加监测频率', NOW(), NOW(), NOW(), '携带支护结构检测设备'),
('矿井供电系统隐患', 17, 'https://registry.npmmirror.com/wot-design-uni-assets/*/files/redpanda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/capybara.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/panda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/moon.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/meng.jpg', '部分电力设备老化，存在短路风险', 1, 1, 0, 17, 'https://registry.npmmirror.com/wot-design-uni-assets/*/files/redpanda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/capybara.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/panda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/moon.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/meng.jpg', '更换老化电力设备，完善应急供电系统', NOW(), NOW(), NOW(), '准备应急发电机'),
('矿井通信系统隐患', 18, 'https://registry.npmmirror.com/wot-design-uni-assets/*/files/redpanda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/capybara.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/panda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/moon.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/meng.jpg', '通信信号覆盖不全面，存在盲区', 0, 3, 1, 18, 'https://registry.npmmirror.com/wot-design-uni-assets/*/files/redpanda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/capybara.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/panda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/moon.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/meng.jpg', '增加信号中继器，扩大信号覆盖范围', NOW(), NOW(), NOW(), '携带通信信号测试设备'),
('矿井消防系统隐患', 19, 'https://registry.npmmirror.com/wot-design-uni-assets/*/files/redpanda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/capybara.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/panda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/moon.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/meng.jpg', '部分消防设备失效，影响火灾应对能力', 1, 2, 0, 19, 'https://registry.npmmirror.com/wot-design-uni-assets/*/files/redpanda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/capybara.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/panda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/moon.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/meng.jpg', '更换失效消防设备，增加消防演练频率', NOW(), NOW(), NOW(), '检查消防设备的有效期'),
('矿井瓦斯监测系统隐患', 20, 'https://registry.npmmirror.com/wot-design-uni-assets/*/files/redpanda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/capybara.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/panda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/moon.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/meng.jpg', '瓦斯监测设备精度下降，可能导致误报或漏报', 0, 1, 1, 20, 'https://registry.npmmirror.com/wot-design-uni-assets/*/files/redpanda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/capybara.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/panda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/moon.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/meng.jpg', '校准瓦斯监测设备，增加备用设备', NOW(), NOW(), NOW(), '携带便携式瓦斯检测仪'),
('矿井提升系统隐患', 21, 'https://registry.npmmirror.com/wot-design-uni-assets/*/files/redpanda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/capybara.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/panda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/moon.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/meng.jpg', '提升机制动系统磨损，存在安全隐患', 1, 3, 0, 21, 'https://registry.npmmirror.com/wot-design-uni-assets/*/files/redpanda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/capybara.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/panda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/moon.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/meng.jpg', '更换制动系统部件，加强日常检查', NOW(), NOW(), NOW(), '准备备用制动系统部件');

-- Generate fake data for rsm_snapshot
INSERT INTO `rsm_snapshot` (`question_title`, `question_desc`, `creator_id`, `img_path`, `handler_id`, `approval_reply`, `property`, `handler_time`, `create_time`, `update_time`, `remark`)
VALUES
('矿井通风系统问题', '矿井通风系统存在有害气体和粉尘吸入风险', 1, 'https://registry.npmmirror.com/wot-design-uni-assets/*/files/redpanda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/capybara.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/panda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/moon.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/meng.jpg', 2, '已确认问题，需立即更换过滤装置并增加通风频率', 0, NOW(), NOW(), NOW(), '需要携带气体检测仪和防尘面具'),
('矿山支护结构问题', '矿山支护结构存在顶板塌陷和片帮冒顶风险', 2, 'https://registry.npmmirror.com/wot-design-uni-assets/*/files/redpanda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/capybara.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/panda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/moon.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/meng.jpg', 3, '问题严重，需立即停止相关区域作业并进行全面检查', 1, NOW(), NOW(), NOW(), '携带专业检测设备，注意安全防护'),
('矿车制动系统问题', '矿车制动系统需要短时间停止运输，影响生产效率', 3, 'https://registry.npmmirror.com/wot-design-uni-assets/*/files/redpanda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/capybara.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/panda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/moon.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/meng.jpg', 1, '同意更换计划，请协调生产部门制定分批次更换方案', 0, NOW(), NOW(), NOW(), '需要提前协调生产计划'),
('井下排水系统问题', '井下排水泵存在老化现象，可能导致排水不畅', 4, 'https://registry.npmmirror.com/wot-design-uni-assets/*/files/redpanda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/capybara.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/panda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/moon.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/meng.jpg', 4, '需要尽快更换老化泵体，并增加一台备用泵', 1, NOW(), NOW(), NOW(), '携带防水设备和应急照明'),
('矿井电力系统问题', '部分电力线路绝缘老化，存在短路风险', 5, 'https://registry.npmmirror.com/wot-design-uni-assets/*/files/redpanda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/capybara.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/panda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/moon.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/meng.jpg', 5, '立即安排专业电工更换老化线路，并加强日常巡检', 1, NOW(), NOW(), NOW(), '需要专业电工和绝缘防护装备'),
('矿井提升系统问题', '提升系统钢丝绳出现磨损，存在断裂风险', 6, 'https://registry.npmmirror.com/wot-design-uni-assets/*/files/redpanda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/capybara.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/panda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/moon.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/meng.jpg', 6, '立即更换磨损钢丝绳，并制定定期检查计划', 1, NOW(), NOW(), NOW(), '需要专业机械工程师'),
('矿井通信系统问题', '部分通信设备信号不稳定，影响井下通讯', 7, 'https://registry.npmmirror.com/wot-design-uni-assets/*/files/redpanda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/capybara.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/panda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/moon.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/meng.jpg', 7, '更换老旧通信设备，优化信号覆盖范围', 0, NOW(), NOW(), NOW(), '携带通信测试设备'),
('矿井消防系统问题', '部分消防设备已过期，存在失效风险', 8, 'https://registry.npmmirror.com/wot-design-uni-assets/*/files/redpanda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/capybara.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/panda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/moon.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/meng.jpg', 8, '立即更换所有过期消防设备，完善消防系统', 1, NOW(), NOW(), NOW(), '检查消防设备的有效期'),
('井下照明系统故障', '部分区域照明设备损坏，影响作业安全', 9, 'https://registry.npmmirror.com/wot-design-uni-assets/*/files/redpanda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/capybara.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/panda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/moon.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/meng.jpg', 9, '立即更换损坏的照明设备，增加应急照明', 0, NOW(), NOW(), NOW(), '携带备用照明设备'),
('矿井通风口堵塞', '主通风口附近堆积大量杂物，影响通风效果', 10, 'https://registry.npmmirror.com/wot-design-uni-assets/*/files/redpanda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/capybara.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/panda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/moon.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/meng.jpg', 10, '立即清理通风口周围杂物，制定定期清理计划', 1, NOW(), NOW(), NOW(), '需要清理工具和防尘设备'),
('井下积水问题', '某区域出现严重积水，影响正常作业', 11, 'https://registry.npmmirror.com/wot-design-uni-assets/*/files/redpanda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/capybara.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/panda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/moon.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/meng.jpg', 11, '立即启动应急排水系统，检查排水设备是否正常', 1, NOW(), NOW(), NOW(), '携带防水装备和应急排水泵'),
('矿井支护结构损坏', '某区域支护结构出现裂缝，存在坍塌风险', 12, 'https://registry.npmmirror.com/wot-design-uni-assets/*/files/redpanda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/capybara.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/panda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/moon.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/meng.jpg', 12, '立即封锁受损区域，安排专业团队进行修复', 1, NOW(), NOW(), NOW(), '需要专业支护修复设备'),
('矿井运输设备故障', '主要运输带出现严重磨损，影响运输效率', 13, 'https://registry.npmmirror.com/wot-design-uni-assets/*/files/redpanda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/capybara.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/panda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/moon.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/meng.jpg', 13, '安排维修人员更换磨损部件，优化运输系统', 0, NOW(), NOW(), NOW(), '准备备用运输设备'),
('矿井安全设备缺失', '某区域缺少必要的安全警示标志，增加安全隐患', 14, 'https://registry.npmmirror.com/wot-design-uni-assets/*/files/redpanda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/capybara.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/panda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/moon.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/meng.jpg', 14, '立即补充安全警示标志，加强安全教育培训', 0, NOW(), NOW(), NOW(), '准备安全警示标志和安装工具'),
('井下粉尘浓度超标', '某采煤工作面粉尘浓度严重超标，威胁工人健康', 15, 'https://registry.npmmirror.com/wot-design-uni-assets/*/files/redpanda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/capybara.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/panda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/moon.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/meng.jpg', 15, '立即加强通风降尘措施，为工人配备高效防尘面具', 1, NOW(), NOW(), NOW(), '携带粉尘检测仪和防尘设备'),
('矿井顶板裂缝', '某巷道顶板出现明显裂缝，存在冒顶风险', 16, 'https://registry.npmmirror.com/wot-design-uni-assets/*/files/redpanda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/capybara.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/panda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/moon.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/meng.jpg', 16, '立即封锁危险区域，安排专业人员进行支护加固', 1, NOW(), NOW(), NOW(), '需要专业支护设备和监测仪器'),
('井下有害气体超标', '某区域甲烷浓度接近警戒线，存在瓦斯爆炸风险', 17, 'https://registry.npmmirror.com/wot-design-uni-assets/*/files/redpanda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/capybara.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/panda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/moon.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/meng.jpg', 17, '立即加强通风排气，暂停该区域作业，进行全面气体检测', 1, NOW(), NOW(), NOW(), '携带便携式气体检测仪和防毒面具'),
('矿井排水系统故障', '主排水泵出现机械故障，影响正常排水', 18, 'https://registry.npmmirror.com/wot-design-uni-assets/*/files/redpanda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/capybara.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/panda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/moon.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/meng.jpg', 18, '立即启动备用排水泵，安排维修人员检修故障泵', 1, NOW(), NOW(), NOW(), '携带备用零件和维修工具'),
('井下电力系统不稳定', '某区域供电线路老化，导致频繁断电', 19, 'https://registry.npmmirror.com/wot-design-uni-assets/*/files/redpanda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/capybara.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/panda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/moon.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/meng.jpg', 19, '更换老化线路，优化供电系统', 0, NOW(), NOW(), NOW(), '需要专业电工和绝缘测试设备'),
('矿井运输轨道变形', '某段运输轨道出现明显变形，影响运输安全', 20, 'https://registry.npmmirror.com/wot-design-uni-assets/*/files/redpanda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/capybara.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/panda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/moon.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/meng.jpg', 20, '立即停止使用变形轨道，安排专业人员进行修复', 1, NOW(), NOW(), NOW(), '携带轨道校正设备'),
('井下温度异常升高', '某区域温度明显高于正常水平，存在火灾隐患', 21, 'https://registry.npmmirror.com/wot-design-uni-assets/*/files/redpanda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/capybara.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/panda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/moon.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/meng.jpg', 21, '加强通风降温，进行全面火源检查', 1, NOW(), NOW(), NOW(), '携带红外测温仪和消防设备'),
('矿井支架液压系统泄漏', '某工作面支架液压油管破裂，影响支护效果', 22, 'https://registry.npmmirror.com/wot-design-uni-assets/*/files/redpanda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/capybara.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/panda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/moon.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/meng.jpg', 22, '立即更换破裂油管，检查其他支架液压系统', 0, NOW(), NOW(), NOW(), '携带备用油管和液压油'),
('井下粉尘爆炸隐患', '某采煤工作面粉尘浓度高，存在粉尘爆炸风险', 23, 'https://registry.npmmirror.com/wot-design-uni-assets/*/files/redpanda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/capybara.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/panda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/moon.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/meng.jpg', 23, '加强喷雾降尘，严格控制电气设备使用', 1, NOW(), NOW(), NOW(), '携带防爆设备和喷雾装置'),
('矿井通风系统故障', '主通风机出现异常噪音，影响通风效果', 24, 'https://registry.npmmirror.com/wot-design-uni-assets/*/files/redpanda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/capybara.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/panda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/moon.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/meng.jpg', 24, '启动备用通风机，安排维修人员检修主通风机', 1, NOW(), NOW(), NOW(), '携带通风机维修工具'),
('井下巷道积水', '某巷道出现大量积水，影响正常通行', 25, 'https://registry.npmmirror.com/wot-design-uni-assets/*/files/redpanda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/capybara.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/panda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/moon.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/meng.jpg', 25, '立即启动应急排水泵，疏通排水系统', 0, NOW(), NOW(), NOW(), '携带便携式排水泵'),
('矿井安全出口堵塞', '某安全出口被杂物堵塞，影响紧急疏散', 26, 'https://registry.npmmirror.com/wot-design-uni-assets/*/files/redpanda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/capybara.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/panda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/moon.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/meng.jpg', 26, '立即清理堵塞物，确保安全出口畅通', 1, NOW(), NOW(), NOW(), '携带清理工具和应急照明'),
('井下运输设备故障', '某运输车辆发动机故障，影响矿石运输', 27, 'https://registry.npmmirror.com/wot-design-uni-assets/*/files/redpanda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/capybara.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/panda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/moon.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/meng.jpg', 27, '安排备用车辆，维修故障车辆', 0, NOW(), NOW(), NOW(), '携带车辆维修工具'),
('井下通讯系统中断', '某区域通讯信号中断，影响应急联络', 28, 'https://registry.npmmirror.com/wot-design-uni-assets/*/files/redpanda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/capybara.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/panda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/moon.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/meng.jpg', 28, '检修通讯设备，临时使用有线通讯', 1, NOW(), NOW(), NOW(), '携带备用通讯设备'),
('矿井支护结构变形', '某巷道支护结构出现明显变形，存在坍塌风险', 29, 'https://registry.npmmirror.com/wot-design-uni-assets/*/files/redpanda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/capybara.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/panda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/moon.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/meng.jpg', 29, '立即加固支护结构，疏散危险区域人员', 1, NOW(), NOW(), NOW(), '携带支护加固材料'),
('井下水仓溢流', '主水仓水位超过警戒线，存在淹井风险', 30, 'https://registry.npmmirror.com/wot-design-uni-assets/*/files/redpanda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/capybara.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/panda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/moon.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/meng.jpg', 30, '启动应急排水系统，加强水位监测', 1, NOW(), NOW(), NOW(), '携带水位监测设备'),
('矿井火灾隐患', '某电气设备冒烟，存在引发火灾风险', 31, 'https://registry.npmmirror.com/wot-design-uni-assets/*/files/redpanda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/capybara.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/panda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/moon.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/meng.jpg', 31, '立即切断电源，使用灭火器处理', 1, NOW(), NOW(), NOW(), '携带灭火设备'),
('井下机电设备故障', '某采煤机出现异常振动，影响生产效率', 32, 'https://registry.npmmirror.com/wot-design-uni-assets/*/files/redpanda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/capybara.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/panda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/moon.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/meng.jpg', 32, '停止使用故障设备，安排维修人员检修', 0, NOW(), NOW(), NOW(), '携带设备维修工具'),
('矿井顶板局部垮塌', '某工作面顶板出现局部垮塌，威胁人员安全', 33, 'https://registry.npmmirror.com/wot-design-uni-assets/*/files/redpanda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/capybara.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/panda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/moon.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/meng.jpg', 33, '立即撤离人员，封锁危险区域', 1, NOW(), NOW(), NOW(), '携带应急支护设备'),
('井下排水管道破裂', '某排水管道出现裂缝，导致排水不畅', 34, 'https://registry.npmmirror.com/wot-design-uni-assets/*/files/redpanda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/capybara.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/panda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/moon.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/meng.jpg', 34, '临时封堵裂缝，更换损坏管段', 0, NOW(), NOW(), NOW(), '携带管道修复工具'),
('矿井瓦斯突出', '某采煤工作面瓦斯浓度突然升高，存在爆炸风险', 35, 'https://registry.npmmirror.com/wot-design-uni-assets/*/files/redpanda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/capybara.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/panda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/moon.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/meng.jpg', 35, '立即撤离人员，加强通风排气', 1, NOW(), NOW(), NOW(), '携带便携式瓦斯检测仪'),
('井下供电系统短路', '某供电线路出现短路，导致局部停电', 36, 'https://registry.npmmirror.com/wot-design-uni-assets/*/files/redpanda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/capybara.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/panda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/moon.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/meng.jpg', 36, '切断故障线路电源，排查短路原因', 1, NOW(), NOW(), NOW(), '携带绝缘检测设备'),
('矿井地压活动异常', '某区域出现明显地压活动，存在冒顶片帮风险', 37, 'https://registry.npmmirror.com/wot-design-uni-assets/*/files/redpanda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/capybara.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/panda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/moon.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/meng.jpg', 37, '加强支护力度，密切监测地压变化', 1, NOW(), NOW(), NOW(), '携带地压监测设备'),
('井下运输系统故障', '某皮带输送机断裂，影响煤炭运输', 38, 'https://registry.npmmirror.com/wot-design-uni-assets/*/files/redpanda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/capybara.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/panda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/moon.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/meng.jpg', 38, '停止使用故障输送机，安排维修更换', 0, NOW(), NOW(), NOW(), '携带皮带修复工具'),
('矿井通风不畅', '某采区风量不足，影响作业环境', 39, 'https://registry.npmmirror.com/wot-design-uni-assets/*/files/redpanda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/capybara.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/panda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/moon.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/meng.jpg', 39, '调整风门开度，增加局部通风机', 1, NOW(), NOW(), NOW(), '携带便携式风量测量仪'),
('井下积水漏电', '某积水区域出现漏电现象，存在触电风险', 40, 'https://registry.npmmirror.com/wot-design-uni-assets/*/files/redpanda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/capybara.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/panda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/moon.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/meng.jpg', 40, '切断电源，排查漏电原因', 1, NOW(), NOW(), NOW(), '携带绝缘防护装备'),
('矿井支护材料短缺', '某工作面支护材料不足，影响正常作业', 40, 'https://registry.npmmirror.com/wot-design-uni-assets/*/files/redpanda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/capybara.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/panda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/moon.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/meng.jpg', 2, '紧急调配支护材料，优化材料使用', 0, NOW(), NOW(), NOW(), '携带临时支护工具'),
('井下设备磨损严重', '某采煤机截割部件磨损严重，影响工作效率', 40, 'https://registry.npmmirror.com/wot-design-uni-assets/*/files/redpanda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/capybara.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/panda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/moon.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/meng.jpg', 1, '更换磨损部件，加强设备维护', 0, NOW(), NOW(), NOW(), '携带备用截割部件'),
('矿井安全设施损坏', '某紧急避险设施损坏，影响应急避险', 40, 'https://registry.npmmirror.com/wot-design-uni-assets/*/files/redpanda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/capybara.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/panda.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/moon.jpg,
      https://registry.npmmirror.com/wot-design-uni-assets/*/files/meng.jpg', 27, '安排备用车辆，维修故障车辆', 0, NOW(), NOW(), NOW(), '携带车辆维修工具');

-- 重新启用外键检查
SET FOREIGN_KEY_CHECKS = 1;