server:
  port: 8080
spring:
  application:
    name: RSM
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://111.230.32.147:3306/ry_vue_temp?useSSL=false&serverTimezone=UTC
    username: root
    password: 4+K/D2zvxHooBhn5begcMQz/04IpAMpq
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.hmdp: DEBUG
#    org.springframework.security: DEBUG
#    org.springframework.boot: DEBUG


#weixin:
#  appid: 'wx49b29dd4bcd70d0b'
#  secret: '9fd7b88e7399987a4c278933de7776e1'
